<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="Firebase.App">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\Firebase.App.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UniTask.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="ICSharpCode.SharpZipLib">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\ICSharpCode.SharpZipLib.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AndroidJNIModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.AndroidJNIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="Firebase.Analytics">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\Firebase.Analytics.dll</HintPath>
    </Reference>
    <Reference Include="Firebase.RemoteConfig">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\Firebase.RemoteConfig.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.UnityAnalyticsModule.dll</HintPath>
    </Reference>
    <Reference Include="Firebase.TaskExtension">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\Firebase.TaskExtension.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Analytics.StandardEvents">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\Unity.Analytics.StandardEvents.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>..\SFS-Multiplayer\SFSMultiPlayer\bin\Debug\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>